#!/usr/bin/env bash

if [ $# -lt 1 ]; then echo "$(basename ${0}): need IP address to check" >&2; exit 1; fi

CMD_JQ=$(which jq)
CMD_CURL=$(which curl)

if [ ! "${CMD_JQ}" ]; then echo "$(basename ${0}): need 'jq' to parse check results" >&2; exit 1; fi

IPADDRESS=${1}
COUNTRY=$(${CMD_CURL} -s --connect-timeout 5 https://ipinfo.io/${IPADDRESS} 2>/dev/null | ${CMD_JQ} -r '.country' | tr '[:upper:]' '[:lower:]' | grep -v ^null)
if [ "${COUNTRY}" = "" ]
then
	echo "$(basename ${0}): Couldn't find country for IP ${IPADDRESS}"
	exit 1
else
	echo ${COUNTRY}
	exit 0
fi
