#!/usr/bin/env bash

if [ $# -le 0 ]; then echo "$(basename ${0}): no UNIX timestamp given" >&2; exit 1; fi

CMD_DATE=$(which date)

if [ "$(which brew)" ]
then
    HOMEBREW_PREFIX="$(brew --prefix)"
    BREW_DATE=${HOMEBREW_PREFIX}/opt/coreutils/libexec/gnubin/date
    if [ -s ${BREW_DATE} ]; then CMD_DATE=${BREW_DATE}; fi
fi

GNU_DATE_DETECT="$(${CMD_DATE} --version 2>&1 | head -1 | grep 'GNU coreutils')"

if [ ! "${GNU_DATE_DETECT}" ]
then
    if [ "$(uname -s | grep Darwin)" ]
    then
        # shellcheck disable=SC2068
        ${CMD_DATE} -j -f "%s" ${@}
    else
        echo "$(basename ${0}): need GNU date to operate correctly" >&2; exit 1
    fi
else
    # shellcheck disable=SC2145
    ${CMD_DATE} --date "@${@}"
fi
