#!/bin/bash

echo " * Checking installed kernels ..."
KERNELS=$(dpkg -l linux-image\* | grep ^ii | grep -v -e "$(uname -a | awk '{print $3}')" -e "linux-image-server" -e "linux-image-generic" | awk '{print $2}' | head -n -1)
echo " - Current kernel: $(dpkg -l linux-image\* | grep ^ii | awk '{print $2}' | grep "$(uname -a | awk '{print $3}')")"
echo " - Latest kernel:  $(dpkg -l linux-image\* | grep ^ii | awk '{print $2}' | grep -v -e "linux-image-server" -e "linux-image-generic" | tail -1)"
echo " - $(echo $KERNELS | wc -w) installed and removable kernels found"
if [ $(echo $KERNELS | wc -w) -gt 0 ]
then
	echo " - Starting kernel removal process ..."
	sudo apt-get remove $KERNELS
	echo " * ... done!"
else
	echo " - No kernels found to remove"
	echo " * ... done!"
fi
