#!/bin/sh

cd ~neuro/host/neuro.me.uk/data/

# cat tech-000-header

cat << EOM
<div align="center"><table border="0" cellpadding="5" cellspacing="0" width="85%">
EOM

for i in tech-001-core tech-active tech-reserves tech-scuttled
do
	COUNT=1
	GREY=0
	case "$i" in
		"tech-001-core")
			LINE_STAT="<em><font color=\"#009900\">in service</strong></em>"
			;;
		"tech-active")
			LINE_STAT="<em><font color=\"#009900\">in service</strong></em>"
			;;
		"tech-reserves")
			LINE_STAT="<em><font color=\"orange\">reserve</strong></em>"
			;;
		"tech-scuttled")
			LINE_STAT="<em><font color=\"red\">scuttled</strong></em>"
			;;
	esac
	cat << EOM
<tr><td></td>
    <td align="center"><strong><u>machine</strong></u></td>
    <td align="center"><strong><u>details</strong></u></td>
    <td align="center"><strong><u>date in service</strong></u></td></tr>
EOM
	while [ $COUNT -lt `cat $i | wc -l` ]
	do
		COUNT=`expr $COUNT + 1`
		if [ $GREY = 1 ]
		then
			GREY=0
			LINE_COLR="#EEEEEE"
		else
			GREY=1
			LINE_COLR="#F8F8F8"
		fi
		LINE=`cat $i | head -$COUNT | tail -1`
		LINE_HOST=`echo $LINE | cut -d, -f1`
		LINE_CLAS=`echo $LINE | cut -d, -f2`
		LINE_HARD=`echo $LINE | cut -d, -f3`
		LINE_DATE=`echo $LINE | cut -d, -f4`
		# LINE_STAT=`echo $LINE | cut -d, -f5`
		LINE_COMM=`echo $LINE | cut -d, -f6`
		LINE_OPSY=`echo $LINE | cut -d, -f7`
		if [ "$LINE_HOST" != "BAIL" ]
		then
			cat << EOM
<tr bgcolor="$LINE_COLR">
    <td>&nbsp;</td>
    <td align="center" valign="center"><strong><tt>$LINE_HOST</tt></strong><br />$LINE_CLAS<br />$LINE_STAT</td>
    <td align="left" valign="top"><strong>$LINE_HARD</strong><br />$LINE_COMM<br />$LINE_OPSY</td>
    <td align="center" valign="center"><strong>$LINE_DATE</strong></td></tr>
EOM
		else
			COUNT=10000000
		fi
	done
done

cat << EOM
</table></div>
EOM
